version: '3.7'
services:
  php-apache:
    container_name: php-apache
    image: asmadas/projet_no_sql-php-apache
    # build:
    #   context: .
    #   dockerfile: Dockerfile.php-apache
    ports:
     - "8080:80"
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
      - /var/www/html/users
    links: 
     - "postgres:container_unposteur"
     - "redis:container_redis"
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports: 
      - "5433:5432"
    restart: unless-stopped
    volumes:
    - postgres_data:/var/lib/postgresql/data:rw
  redis:
    container_name: "redis"
    image: redis:latest
    ports:
      - "6379:6379"
    command:
        --requirepass ${REDIS_PWD}
    volumes:
    - "redis_data:/data"

volumes:
  postgres_data: {}
  redis_data: {}