version: '3.7'
services:
  php-apache:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile.php-apache
    ports:
     - "8080:80"
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
    links: 
     - "postgres:container_unposteur"
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: unposteur
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports: 
      - "5433:5432"
    restart: unless-stopped
    volumes:
    - postgres_data:/var/lib/postgresql/data:rw

volumes:
  postgres_data: {}
