FROM php:7.4-apache
RUN apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pgsql
RUN pecl install redis && \
    docker-php-ext-enable redis
RUN mkdir /var/www/html/users
RUN chown -R www-data /var/www/html/users/